site_name: Документация по курсу WEB-программирование
theme:
  name: material

nav:
  - Лабораторная работа №1:
      - Краткое описание: LR1/index.md
      - Задание №1: LR1/Task №1.md
      - Задание №2: LR1/Task №2.md
      - Задание №3: LR1/Task №3.md
      - Задание №4: LR1/Task №4.md
      - Задание №5: LR1/Task №5.md
  - Лабораторная работа №2:
      - Краткое описание: LR2/index.md
      - Задание №1: LR2/Task №1.md